<?xml version="1.0"?>
<package format="3">
  <name>bringup</name>
  <version>0.1.0</version>
  <description>Launch composition for the cone harvest robot.</description>
  <maintainer email="chldbwls08@seoultech.ac.kr">youjins18</maintainer>
  <license>TODO</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>arm_controller</exec_depend>
  <exec_depend>chr_commander</exec_depend>
  <exec_depend>chr_controller</exec_depend>
  <exec_depend>chr_mujoco</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>palletrone_flight_controller</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
